services:
  test-app-rabbitmq:
    image: rabbitmq:3.12.12-management
    container_name: test-app-rabbitmq
    hostname: rabbit
    restart: always
    ports:
      - "5672:${RABBITMQ_PORT}"
      - 15671:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 10
  test-app-db:
    image: postgres:15
    container_name: test-app-pg
    restart: always
    expose:
      - "${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}'" ]
      interval: 4s
      timeout: 3s
      retries: 3
  test-app-redis:
    image: redis:7
    restart: always
    ports:
      - "6380:${REDIS_PORT}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
  test-localstack:
    image: localstack/localstack:3.0
    container_name: test-localstack
    hostname: localstack
    ports:
      - 4567:4566
      - 8081:8082
    environment:
      - SERVICES=s3
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
    env_file:
      - .test.env
    volumes:
      - ./src/scripts/localstack_script.sh:/etc/localstack/init/ready.d/script.sh
      - "/var/run/docker.sock:/var/run/docker.sock"
  test-app:
    platform: linux/x86-64
    container_name: test-app
    build: .
    entrypoint: sh -c "./src/scripts/entrypoint_tests.sh"
    ports:
      - "8001:${PORT}"
    env_file:
      - .test.env
    volumes:
      - .:/home/appuser
    depends_on:
      test-app-db:
        condition: service_healthy
      test-app-redis:
        condition: service_started
      test-app-rabbitmq:
        condition: service_healthy
      test-localstack:
        condition: service_started
