"""Added onupdate for modified_at

Revision ID: 12f98a7034fd
Revises: dabe2eab704f
Create Date: 2024-01-14 21:45:17.521089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12f98a7034fd"
down_revision: Union[str, None] = "dabe2eab704f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
