"""Database creation

Revision ID: 422d647f328c
Revises:
Create Date: 2023-12-16 01:31:00.194548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "422d647f328c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("ID", sa.UUID(), nullable=False),
        sa.Column("Name", sa.String(length=15), nullable=False),
        sa.Column("Created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ID"),
        sa.UniqueConstraint("Name"),
    )
    op.create_index("idx_unique_name", "groups", ["Name"], unique=True)
    op.create_index(op.f("ix_groups_ID"), "groups", ["ID"], unique=False)
    op.create_table(
        "users",
        sa.Column("ID", sa.UUID(), nullable=False),
        sa.Column("Name", sa.String(length=15), nullable=True),
        sa.Column("Surname", sa.String(length=15), nullable=True),
        sa.Column("Phone_number", sa.String(length=15), nullable=True),
        sa.Column("Email", sa.String(), nullable=False),
        sa.Column(
            "Role",
            sa.Enum("USER", "ADMIN", "MODERATOR", name="role_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("Group_id", sa.UUID(), nullable=False),
        sa.Column("Image", sa.String(), nullable=True),
        sa.Column("IsBlocked", sa.Boolean(), nullable=False),
        sa.Column("Created_at", sa.DateTime(), nullable=False),
        sa.Column("Modified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["Group_id"],
            ["groups.ID"],
        ),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_index(op.f("ix_users_ID"), "users", ["ID"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_ID"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_groups_ID"), table_name="groups")
    op.drop_index("idx_unique_name", table_name="groups")
    op.drop_table("groups")
    # ### end Alembic commands ###
