"""Database creation

Revision ID: 975471a12575
Revises:
Create Date: 2023-12-15 12:25:55.557823

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "975471a12575"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("ID", sa.Integer(), nullable=False),
        sa.Column("Name", sa.String(), nullable=False),
        sa.Column("Created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_index(op.f("ix_groups_ID"), "groups", ["ID"], unique=False)
    op.create_table(
        "users",
        sa.Column("ID", sa.UUID(), nullable=False),
        sa.Column("Name", sa.String(), nullable=False),
        sa.Column("Surname", sa.String(), nullable=False),
        sa.Column("Phone_number", sa.String(), nullable=False),
        sa.Column("Email", sa.String(), nullable=False),
        sa.Column(
            "Role",
            sa.Enum("USER", "ADMIN", "MODERATOR", name="role_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("Group_id", sa.Integer(), nullable=False),
        sa.Column("Image", sa.String(), nullable=False),
        sa.Column("IsBlocked", sa.Boolean(), nullable=False),
        sa.Column("Created_at", sa.DateTime(), nullable=False),
        sa.Column("Modified_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["Group_id"],
            ["groups.ID"],
        ),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_index(op.f("ix_users_ID"), "users", ["ID"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_ID"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_groups_ID"), table_name="groups")
    op.drop_table("groups")
    # ### end Alembic commands ###
